export const FETCH_STUDENTS_LIST = 'FETCH_STUDENTS_LIST'
export const FETCH_STUDENTS_LIST_SUCCESS = 'FETCH_STUDENLIST_TS_SUCCESS'
export const FETCH_STUDENTS_LIST_FAILURE = 'FETCH_STUDENTS_LIST_FAILURE'

export const FETCH_STUDENT_DETAILS = 'FETCH_STUDENT_DETAILS'
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS'
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE'

export const ADD_STUDENT = 'ADD_STUDENT'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE'

export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'

export const FETCH_PROJECTS_LIST = 'FETCH_PROJECTS_LIST'
export const FETCH_PROJECTS_LIST_SUCCESS = 'FETCH_PROJECTS_LIST_SUCCESS'
export const FETCH_PROJECTS_LIST_FAILURE = 'FETCH_PROJECTS_LIST_FAILURE'

export const FETCH_PROJECT_DETAILS = 'FETCH_PROJECT_DETAILS'
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE'

export const ADD_PROJECT = 'ADD_PROJECT'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'