export const FETCH_STUDENTS_LIST = 'FETCH_STUDENTS_LIST'
export const FETCH_STUDENTS_LIST_SUCCESS = 'FETCH_STUDENLIST_TS_SUCCESS'
export const FETCH_STUDENTS_LIST_FAILURE = 'FETCH_STUDENTS_LIST_FAILURE'

export const FETCH_STUDENT_DETAILS = 'FETCH_STUDENT_DETAILS'
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS'
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE'

export const FETCH_PROJECTS_LIST = 'FETCH_PROJECTS_LIST'
export const FETCH_PROJECTS_LIST_SUCCESS = 'FETCH_PROJECTS_LIST_SUCCESS'
export const FETCH_PROJECTS_LIST_FAILURE = 'FETCH_PROJECTS_LIST_FAILURE'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'