export const FETCH_STUDENTS_LIST = 'FETCH_STUDENTS_LIST'
export const FETCH_STUDENTS_LIST_SUCCESS = 'FETCH_STUDENLIST_TS_SUCCESS'
export const FETCH_STUDENTS_LIST_FAILURE = 'FETCH_STUDENTS_LIST_FAILURE'

export const FETCH_STUDENT_DETAILS = 'FETCH_STUDENT_DETAILS'
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS'
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE'